--- 
- message: Thread 5 caught an exception.
  :work: /Users/tyler/article_test/articles/19563
  :exception: No such file or directory - /Users/tyler/article_test/articles/19563/new_article.yaml
  :backtrace: 
  - extract_external_links.rb:46:in `initialize'
  - extract_external_links.rb:46:in `open'
  - extract_external_links.rb:46:in `get_yaml'
  - extract_external_links.rb:18:in `block in main'
  - /Users/tyler/scripts/test_articles/lib/threadpool.rb:28:in `call'
  - /Users/tyler/scripts/test_articles/lib/threadpool.rb:28:in `block (3 levels) in run'
  - /Users/tyler/scripts/test_articles/lib/threadpool.rb:62:in `call'
  - /Users/tyler/scripts/test_articles/lib/threadpool.rb:62:in `thread_method'
  - /Users/tyler/scripts/test_articles/lib/threadpool.rb:27:in `block (2 levels) in run'
